### ISSUE TITLE
Feature request: Use pyinstaller for stand alone app.

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/SummerCart64#28]
## Expected Behavior
Ease of use for average user.

## Current Behavior
Requires python and dependencies to be installed.

## Possible Solution
Installing python should not really be required for the average user, so let's generate a standalone application as part of the release process... at least for the loader.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Mainly a windows environment.

## Possible Implementation

Use something like pyinstaller.

**Comment by Polprzewodnikowy** [comment]
I've added workflow job for that feature in this PR: https://github.com/Polprzewodnikowy/SummerCart64/pull/29. It definitely needs some more work. I've used `--onefile` parameter but executable takes several seconds to load and print any output. Documentation also needs to be adjusted if we want users to download precompiled apps instead of using python script direcly.

**Comment by networkfusion** [comment]
Nice work. I have been digging a little deeper (with only mobile access) and an alternative might be to use https://github.com/Nuitka/Nuitka instead or pyinstaller, although not sure if it will be any better.

**Comment by networkfusion** [comment]
Or a possible fix could be https://github.com/pyinstaller/pyinstaller/issues/2550 but at this point I am only speculating. I can help from tues onwards.

**Comment by Polprzewodnikowy** [comment]
Fiddled a little bit with parameters and it's pretty quick on Windows and Linux. App starts and it's operational in less than half a second. macOS build on other hand requires 2-4 seconds to print anything at all. I don't think this is a big issue because python3 is preinstalled in macOS so user don't have to install it separately. Only additional step is installing requirements in that case.

**Comment by networkfusion** [comment]
Interestingly Windows Defender thinks that the generated `sc64.exe` contains a trojan!. I will fork the branch and see if I can work out why. Also, it seems to take at least a couple of seconds to load, so I will see if I can improve that as well.

**Comment by Polprzewodnikowy** [comment]
Building pyinstaller bootloader separately seems to fix the issue with false virus detection. I ran tests on VirusTotal with file built from latest action on `pyinstaller` branch and zero threats were detected. macOS build still has issue with very long bootup time that needs further investigation. Documentation also should be adjusted to point the user to download precompiled binaries.

**Comment by networkfusion** [comment]
I have also been playing with this here: https://github.com/networkfusion/SummerCollection/tree/nuitka
But.. got distracted by the menu 😜

**Comment by Polprzewodnikowy** [comment]
Fixed in https://github.com/Polprzewodnikowy/SummerCart64/commit/5b2ee0b6a1188166afc1dd57bb1a886841b354e3
