### ISSUE TITLE
Densha De Go! English Translation patch - timer never counts down

### ISSUE THREAD

**Issue by zarikov** [Polprzewodnikowy/SummerCart64#79]
**Describe the bug**
The fan translation of Densha De Go!'s in-game timer doesn't tick down. The original japanese version however does not have this issue on the Sumercart64, and the game generally appears to work as intended as far as I can tell.

firmware version: 2.18.1

**To Reproduce**
1. start game
2. mash A until it starts any level

**Screenshots**
![Untitled-1](https://github.com/user-attachments/assets/791b49e6-bbd9-4a58-a20c-84ae0fc2fe0f)
countdown timer outlined in red

**Expected behavior**
the timers should tick down to indicate how much time has passed

**Possible solution**
I notified the patch creator Zoinkity about this, and it sounds like this has been an issue on other 64 flashcarts. The translation can be found here: https://www.romhacking.net/translations/2947/

This game has 64DD support in the sense that if it detects a 64DD the menu shows a different train... no idea if that could possibly matter but figured I'd throw it in.

**Comment by Polprzewodnikowy** [comment]
What I'm supposed to do with this issue? It's a bug in the translation, not in the flashcart firmware. It happens even on other flashcarts as you noticed.

I would look into it if it was a normal retail game, not a buggy romhack.

**Comment by zarikov** [comment]
ok

**Comment by arnauos** [comment]
Hi, it seems the translation patch [was updated](https://www.romhacking.net/forum/index.php?topic=39726.msg462662#msg462662) to support SummerCart64. Use new version 1.02.

> English translation patches for Puyo Puyo Sun 64 and Densha de Go! 64 have been updated to support SummerCart64.
It also shares the same bonus features as the 64drive; rather handy, since those aren't being produced any longer.
In addition to some boring bugfixes, Densha de Go now has a gallery feature if you take screenshots with the debugger.
