### ISSUE TITLE
MiSTer FPGA acting as SummerCart64 / source of mappers, code for future projects?

### ISSUE THREAD

**Issue by jan-kleks** [Polprzewodnikowy/SummerCart64#92]
Recently we can see new affordable MiSTer FPGA boards hitting the market: https://www.retrorgb.com/mister-pi-de-10-nano-clone-up-for-sale-today.html

Could MiSTer FPGA be turned (with a proper converter) into a kind of SummerCart64? Here you can see, the board utilized by the MiSTer project acting as a "Game Genie" device: https://www.youtube.com/watch?v=lXTxKD8-ghg Many homebrewers and emulator creators would probably sooner or later get some kind of MiSTer FPGA board -- so flashcart functionality could be useful for testing against original hardware.

Also, the MiSTer project seems to be a great resource for various mappers (NES, for example) and other retro devices' code. Maybe it could be utilized in future open-source flashcart projects?

Keep up the great work!

**Comment by Polprzewodnikowy** [comment]
My general advise is that everything is possible if you put some work in it. SC64 code attempts to be platform agnostic with some parts of it abstracted that need to be ported to the target platform. However, in the case of the board you linked most of the existing modules in the SC64 code base are incompatible with the hardware present on these boards. It's better to come up with a new design that takes supporting chips on the De-10 Nano/MiSTer Pi into the account instead of trying to shove purpose made code onto these boards.

Anyways, this is outside of the scope of this repository and I'm not planning to port the code to other boards. There was an attempt to port the code to Sipeed Tang Primer 20K by someone on the N64brew discord server so you might ask more about it there.
